name: Compile CV

on: push

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: typst-community/setup-typst@v4
        with:
          typst-version: 0.13.1

      # 🎉 Now Typst is installed!

      - run: mkdir .output
      - run: typst compile main.typ .output/Thom-Bruce_CV.pdf --font-path=assets/fonts

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: CV
          path: .output/Thom-Bruce_CV.pdf

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: .output/Thom-Bruce_CV.pdf
