name: Compile CV

on: push

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: sudo apt update
      # - run: sudo apt install fonts-fira

      # This is an annoying way about this, as the google-fonts download is huge...
      # ...and we really just need the one. I need to find a better way to just pull fira-sans.
      - run: mkdir -p ~/.fonts
      - run: wget https://github.com/google/fonts/archive/refs/heads/main.zip -O google-fonts.zip
      - run: unzip google-fonts.zip -d ~/.fonts

      - run: sudo apt install fonts-font-awesome

      - run: fc-cache -fv

      - uses: typst-community/setup-typst@v4
        with:
          typst-version: 0.13.1

      # 🎉 Now Typst is installed!

      - run: typst compile main.typ .output/main.pdf

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: "*.pdf"

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: .output/main.pdf
